import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const load = path => readFile(new URL(`../${path}`, import.meta.url), 'utf8');

test('employee entrypoint busts cache for current phone modal assets', async () => { const html = await load('index.html'); assert.match(html, /src\/styles\.css\?v=18/); assert.match(html, /src\/app\.js\?v=43/); });
test('employee UI source contains no replacement-character text', async () => assert.doesNotMatch(await load('src/app.js'), /\uFFFD/));
test('basic fields are read-only where required', async () => { const app = await load('src/app.js'); assert.match(app, /readonlyBasicFields = new Set\(\['alias', 'socialSecurityLocation'\]\)/); assert.match(app, /rows\(\{ fields \}, \{ \.\.\.data, idNo: maskId/); });
test('identity and household fields use different forms', async () => { const app = await load('src/app.js'); assert.match(app, /identityFields = new Set\(\['name', 'gender', 'idType', 'idNo', 'birthDate', 'ethnicity', 'nativePlace'\]\)/); assert.match(app, /householdFields = new Set\(\['householdType', 'householdAddress'\]\)/); assert.match(app, /new Set\(\['email', 'address', 'politicalStatus', 'maritalStatus'\]\)/); assert.match(app, /upload\('household-attachment'/); assert.doesNotMatch(app, /marriageDate|householdBook|household-book/); });
test('phone edit flow follows verification limits', async () => { const app = await load('src/app.js'); assert.match(app, /route\.mode === 'phone'/); assert.match(app, /send-phone-code/); assert.match(app, /phoneVerification/); assert.match(app, /oldPhone/); assert.match(app, /newPhone/); assert.match(app, /canSendPhoneCode/); assert.match(app, /dailySendCount >= 9999/); assert.match(app, /操作太频繁，请明天再试/); assert.match(app, /60000/); assert.match(app, /function generatePhoneCode\(\) \{ return '123456'; \}/); assert.match(app, /\^1\[3-9\]\\d\{9\}\$/); });
test('phone edit flow follows latest PRD copy and rules', async () => { const app = await load('src/app.js'); for (const copy of ['\u624b\u673a\u53f7\u6bcf\u4e2a\u6708\u53ea\u80fd\u4fee\u6539\u4e00\u6b21\uff0c\u6bcf\u5e74\u53ea\u80fd\u4fee\u65393\u6b21', '\u4f60\u6b63\u5728\u4fee\u6539\u624b\u673a\u53f7', '\u5982\u679c\u65e0\u6cd5\u6536\u5230\u9a8c\u8bc1\u7801\uff0c\u8bf7\u8054\u7cfbHR\u4fee\u6539', '\u4fee\u6539\u624b\u673a\u53f7\u4e4b\u524d\u8bf7\u5148\u8fdb\u884c\u8eab\u4efd', '\u8bf7\u8f93\u5165\u6709\u6548\u7684\u624b\u673a\u53f7', '\u65b0\u624b\u673a\u53f7\u4e0e\u5f53\u524d\u7ed1\u5b9a\u7684\u624b\u673a\u53f7\u76f8\u540c\uff0c\u8bf7\u66f4\u6362\u5176\u4ed6\u624b\u673a\u53f7', '\u624b\u673a\u53f7\u548c\u5728\u804c\u5458\u5de5\u7684\u624b\u673a\u53f7\u91cd\u590d\uff0c\u8bf7\u66f4\u6362\u5176\u4ed6\u624b\u673a\u53f7', '\u8bf7\u8f93\u51656\u4f4d\u9a8c\u8bc1\u7801\uff0c10\u5206\u949f\u5185\u6709\u6548', '\u79d2\u540e\u53ef\u4ee5\u91cd\u65b0\u83b7\u53d6\u9a8c\u8bc1\u7801', '\u91cd\u65b0\u83b7\u53d6\u9a8c\u8bc1\u7801', '\u64cd\u4f5c\u592a\u9891\u7e41\uff0c\u8bf7\u660e\u5929\u518d\u8bd5\u3002', '\u786e\u8ba4\u63d0\u4ea4\u624b\u673a\u53f7\u4fee\u6539\uff1f', '\u63d0\u4ea4\u540e\uff0c\u7cfb\u7edf\u5c06\u66f4\u65b0\u4f60\u7684\u5458\u5de5\u4fe1\u606f\u624b\u673a\u53f7\u3002', '\u98de\u4e66\u767b\u5f55\u624b\u673a\u53f7\u4e0d\u4f1a\u540c\u6b65\u4fee\u6539', '\u4e2a\u4eba\u5934\u50cf &gt; \u8bbe\u7f6e &gt; \u8d26\u53f7\u4e0e\u5b89\u5168 &gt; \u524d\u5f80\u8d26\u53f7\u5b89\u5168\u4e2d\u5fc3 &gt; \u767b\u5f55\u65b9\u5f0f', '\u786e\u8ba4\u63d0\u4ea4']) assert.match(app, new RegExp(copy)); assert.match(app, /activeEmployeePhones/); assert.match(app, /phoneModifiedHistory/); assert.match(app, /currentYearKey/); assert.match(app, /Date\.now\(\) - verify\.lastSentAt > 600000/); assert.match(app, /pendingPhoneChange/); assert.match(app, /confirm-phone-change/); assert.match(app, /phoneStep/); assert.match(app, /send-old-phone-code/); assert.match(app, /send-new-phone-code/); });
test('phone code cooldown renders countdown as the button text only', async () => { const app = await load('src/app.js'); assert.match(app, /phoneCodeButtonText/); assert.match(app, /phoneCodeDisabled/); assert.doesNotMatch(app, /\$\{oldLimit\.reason\}/); assert.doesNotMatch(app, /\$\{newLimit\.reason\}/); });
test('phone change warning opens as a modal after tapping modify and new phone step only asks for the new phone', async () => { const app = await load('src/app.js'); assert.match(app, /phoneIntroModalOpen/); assert.match(app, /data-action="confirm-phone-intro"/); assert.match(app, /const start = `(?:(?!你正在修改手机号)[\s\S])*?`; const identity =/); assert.match(app, /const identity = `(?:(?!你正在修改手机号)[\s\S])*?`; const change =/); assert.match(app, /const introModal = phoneIntroModalOpen \? `[\s\S]*?你正在修改手机号[\s\S]*?` : ''/); assert.match(app, /<h2 class="form-title">请输入新手机号<\/h2>[\s\S]*?<section class="form-card"><div class="field"><label for="newPhone">新手机号<\/label>/); assert.doesNotMatch(app, /const change = `[\s\S]*?<label>旧手机号<\/label>[\s\S]*?`; const body =/); });
test('phone entry and identity copy use the requested labels and plain note style', async () => { const app = await load('src/app.js'); assert.match(app, /const start = `<section class="form-card"><div class="field"><label>手机号<\/label>[\s\S]*?<\/section>\$\{limitNotice\}`/); assert.doesNotMatch(app, /const start = `[\s\S]*?手机号每个月只能修改一次，每年只能修改3次[\s\S]*?`; const identity =/); assert.match(app, /<p>请注意：<\/p><p>1、手机号每个月只能修改一次，每年只能修改3次<\/p><p>2、飞书登录手机号不会同步变更/); assert.match(app, /<p class="plain-note">修改手机号之前请先进行身份验证。<\/p>/); assert.doesNotMatch(app, /<div class="notice">修改手机号之前请先进行身份验证。<\/div>/); });
test('phone code notice only shows validity and HR help copy', async () => { const app = await load('src/app.js'); assert.match(app, /return '<div class="notice">请输入6位验证码，10分钟内有效。<\/div>'/); assert.match(app, /phoneHelpNotice/); assert.match(app, /如果无法收到验证码，请联系HR修改/); assert.doesNotMatch(app, /Demo 验证码为/); assert.doesNotMatch(app, /今日已发送/); });
test('phone verification timeout uses the requested submit error copy', async () => { const app = await load('src/app.js'); assert.match(app, /验证码已超时，请重新获取/); assert.doesNotMatch(app, /验证码已过期，请重新获取验证码/); });
test('phone send limit messages are rendered inline instead of browser alerts', async () => { const app = await load('src/app.js'); assert.match(app, /phoneLimitMessage/); assert.match(app, /showPhoneLimit/); assert.doesNotMatch(app, /window\.alert\(limit\.reason\)/); assert.match(app, /<div class="notice danger">\$\{esc\(phoneLimitMessage\)\}<\/div>/); });
test('phone modification quota is informational and does not block verification', async () => { const app = await load('src/app.js'); assert.match(app, /phoneModifiedMonth = currentMonthKey/); assert.doesNotMatch(app, /showPhoneLimit\('手机号每个月只能修改一次，每年只能修改3次'\)/); assert.doesNotMatch(app, /window\.alert\('手机号每个月只能修改一次，每年只能修改3次'\)/); assert.doesNotMatch(app, /phoneLimitNotice\(oldLimit\)/); });
test('work and family edit buttons are direct save buttons', async () => { const app = await load('src/app.js'); assert.match(app, /const directSaveRecordSections = new Set\(\['work', 'family'\]\)/); assert.match(app, /directSaveRecordSections\.has\(key\)/); });
test('education includes highest-degree option', async () => assert.match(await load('src/app.js'), /highestDegree: '\\u662f\\u5426\\u6700\\u9ad8\\u5b66\\u5386'/));
test('home summary uses the requested default fields and masks', async () => { const app = await load('src/app.js'); assert.match(app, /'alias', 'name', 'gender', 'birthDate', 'idNo', 'ethnicity', 'nativePlace', 'phone'/); assert.doesNotMatch(app, /defaults = new Set\([^\n]*'socialSecurityLocation'/); assert.match(app, /function maskBankCard/); assert.match(app, /function ageOf/); });
