import { createInitialState, getVisibleData, saveSection, submitSection, withdrawSection, submitRecord, withdrawRecord, submitEmergencyFromFamily } from './domain.js';

const STORAGE_KEY = 'atour-personal-info-demo-v9';
const recordKeys = new Set(['education', 'family', 'work', 'certificate']);
const identityFields = new Set(['name', 'gender', 'idType', 'idNo', 'birthDate', 'ethnicity', 'nativePlace']);
const householdFields = new Set(['householdBook', 'householdType', 'householdAddress', 'maritalStatus', 'marriageDate']);
const readonlyBasicFields = new Set(['alias', 'phone', 'socialSecurityLocation']);
const sections = {
  basic: { title: '\u4e2a\u4eba\u57fa\u672c\u4fe1\u606f', fields: { alias: '\u82b1\u540d', name: '\u59d3\u540d', gender: '\u6027\u522b', phone: '\u624b\u673a\u53f7', email: '\u4e2a\u4eba\u90ae\u7bb1', socialSecurityLocation: '\u793e\u4fdd\u7f34\u7eb3\u5730', idType: '\u8bc1\u4ef6\u7c7b\u578b', idNo: '\u8eab\u4efd\u8bc1\u53f7\u7801', birthDate: '\u51fa\u751f\u65e5\u671f', ethnicity: '\u6c11\u65cf', nativePlace: '\u7c4d\u8d2f', address: '\u73b0\u5c45\u4f4f\u5730\u5740', maritalStatus: '\u5a5a\u59fb\u72b6\u51b5', marriageDate: '\u7ed3\u5a5a\u65e5\u671f', politicalStatus: '\u653f\u6cbb\u9762\u8c8c', householdType: '\u6237\u53e3\u6027\u8d28', householdAddress: '\u6237\u7c4d\u6240\u5728\u5730', householdBook: '\u6237\u53e3\u672c\u672c\u4eba\u9875' } },
  bank: { title: '\u94f6\u884c\u5361\u4fe1\u606f', fields: { bank: '\u5f00\u6237\u94f6\u884c', city: '\u5f00\u6237\u57ce\u5e02', branch: '\u5f00\u6237\u652f\u884c', cardNo: '\u94f6\u884c\u5361\u53f7', attachment: '\u94f6\u884c\u5361' } },
  education: { title: '\u6559\u80b2\u4fe1\u606f', fields: { startDate: '\u5f00\u59cb\u65e5\u671f', endDate: '\u7ed3\u675f\u65e5\u671f', school: '\u6bd5\u4e1a\u5b66\u6821', degree: '\u5b66\u5386', major: '\u4e13\u4e1a', highestDegree: '\u662f\u5426\u6700\u9ad8\u5b66\u5386', degreeCertificate: '\u5b66\u4f4d\u8bc1\u4e66', diplomaCertificate: '\u5b66\u5386\u8bc1\u4e66', otherAttachments: '\u5176\u4ed6\u9644\u4ef6' }, add: '\u65b0\u589e\u6559\u80b2\u7ecf\u5386' },
  work: { title: '\u5de5\u4f5c\u5c65\u5386', fields: { startDate: '\u5f00\u59cb\u65e5\u671f', endDate: '\u7ed3\u675f\u65e5\u671f', company: '\u516c\u53f8\u540d\u79f0', role: '\u804c\u4f4d' }, add: '\u65b0\u589e\u5de5\u4f5c\u7ecf\u5386' },
  family: { title: '\u5bb6\u5ead\u4fe1\u606f', fields: { name: '\u59d3\u540d', relation: '\u5173\u7cfb', birthDate: '\u51fa\u751f\u65e5\u671f', phone: '\u8054\u7cfb\u7535\u8bdd' }, add: '\u65b0\u589e\u5bb6\u5ead\u6210\u5458' },
  emergency: { title: '\u7d27\u6025\u8054\u7cfb\u4eba', fields: { name: '\u59d3\u540d', relation: '\u5173\u7cfb', phone: '\u8054\u7cfb\u65b9\u5f0f' } }
};
let state = loadState(), route = { page: 'home' }, files = [], basicExpanded = false;
const app = document.querySelector('#app');
function loadState() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY))?.sections ? JSON.parse(localStorage.getItem(STORAGE_KEY)) : createInitialState(); } catch { return createInitialState(); } }
function persist() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function esc(value = '') { return String(value).replace(/[&<>\"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]); }
function valueOf(value) { return esc(value || '\u6682\u65e0'); }
function maskId(value = '') { const raw = String(value).replace(/\s/g, ''); return raw.length > 7 ? `${raw.slice(0, 3)}${'*'.repeat(raw.length - 7)}${raw.slice(-4)}` : raw; }
function maskPhone(value = '') { const raw = String(value).replace(/\s/g, ''); return raw.length > 7 ? `${raw.slice(0, 3)}${'*'.repeat(raw.length - 7)}${raw.slice(-4)}` : raw; }
function maskBankCard(value = '') { const raw = String(value).replace(/\s/g, ''); return raw.length > 8 ? `${raw.slice(0, 4)} **** **** ${raw.slice(-4)}` : raw; }
function ageOf(birthDate) { if (!birthDate) return ''; const today = new Date(); const birthday = new Date(birthDate); let age = today.getFullYear() - birthday.getFullYear(); if (today.getMonth() < birthday.getMonth() || (today.getMonth() === birthday.getMonth() && today.getDate() < birthday.getDate())) age -= 1; return `${age}\u5c81`; }
function nav(title, back = false) { return `<header class="nav">${back ? '<button class="icon-btn" data-action="back">&lt;</button>' : '<span class="nav-spacer"></span>'}<h1>${title}</h1><span class="nav-spacer"></span></header>`; }
function group(key) { return identityFields.has(key) ? 'identity' : householdFields.has(key) ? 'household' : 'personal'; }
function status(section) { return section.status === 'pending' ? '<span class="status">\u5f85\u5ba1\u6838</span>' : section.status === 'rejected' ? '<span class="status rejected">\u5df2\u9a73\u56de</span>' : ''; }
function notice(section) { return section.status === 'pending' ? '<div class="notice">\u4fe1\u606f\u5df2\u63d0\u4ea4\uff0c\u6b63\u5728\u5ba1\u6838\u4e2d\u3002\u5ba1\u6838\u671f\u95f4\u4e0d\u652f\u6301\u518d\u6b21\u4fee\u6539\uff0c\u53ef\u64a4\u56de\u7533\u8bf7\u3002</div>' : ''; }
function rows(meta, data, clickable = false, sectionKey = '', readonly = new Set()) { return Object.entries(meta.fields).map(([key, label]) => { const edit = clickable && !readonly.has(key); return `<div class="data-row ${edit ? 'clickable' : ''}" ${edit ? `data-section="${sectionKey}" data-field-group="${group(key)}"` : ''}><span>${label}</span><span>${valueOf(data[key])}${edit ? '<b class="chevron">&gt;</b>' : ''}</span></div>`; }).join(''); }
function head(key, edit = '') { return `<div class="module-head"><h2>${sections[key].title}</h2><div>${status(state.sections[key])}${edit}</div></div>`; }
function renderBasicSection() { const section = state.sections.basic, data = getVisibleData(section); const defaults = new Set(['alias', 'name', 'gender', 'birthDate', 'idNo', 'ethnicity', 'nativePlace', 'phone']); const fields = Object.fromEntries(Object.entries(sections.basic.fields).filter(([key]) => !['householdBook'].includes(key) && (basicExpanded || defaults.has(key)))); return `<section class="info-module module-card" id="module-basic">${head('basic')}${notice(section)}<div class="detail-card">${rows({ fields }, { ...data, idNo: maskId(data.idNo), phone: maskPhone(data.phone) }, section.status !== 'pending', 'basic', readonlyBasicFields)}</div><button class="show-more" data-action="toggle-basic">${basicExpanded ? '\u6536\u8d77' : '\u663e\u793a\u66f4\u591a'} &gt;</button></section>`; }
function summary(key, record) { if (key === 'family') return `<div class="record-summary family-summary"><span class="record-subtitle">${valueOf(record.name)} \u00b7 ${valueOf(record.relation)}</span><strong class="record-primary">${ageOf(record.birthDate)}</strong></div>`; const values = key === 'education' ? [`${record.startDate || ''} - ${record.endDate || ''} \u00b7 ${record.school || ''}`, record.degree, record.major] : [`${record.startDate || ''} - ${record.endDate || ''} \u00b7 ${record.company || ''}`, record.role, '']; return `<div class="record-summary"><span class="record-time">${valueOf(values[0])}</span><span class="record-subtitle">${valueOf(values[1])}</span><strong class="record-primary">${valueOf(values[2])}</strong></div>`; }
function renderRecordSection(key) { const section = state.sections[key], requests = section.recordRequests || []; const pending = new Map(requests.filter(item => item.recordId).map(item => [item.recordId, item])); const cards = section.approvedData.map(record => { const request = pending.get(record.id), shown = request?.operation === 'edit' ? request.draft : record; return `<article class="record-card record-summary-card ${request ? `pending-${request.operation}` : ''}" ${request ? `data-section="${key}" data-request="${request.requestId}" data-action="view-pending"` : `data-section="${key}" data-record-edit="${record.id}"`}>${request ? `<span class="record-status">${request.operation === 'edit' ? '\u4fee\u6539\u5f85\u5ba1\u6838' : '\u5220\u9664\u5f85\u5ba1\u6838'}</span>` : '<span class="record-chevron">&gt;</span>'}${summary(key, shown)}</article>`; }).join(''); const additions = requests.filter(item => item.operation === 'add').map(item => `<article class="record-card record-summary-card pending-add" data-section="${key}" data-request="${item.requestId}" data-action="view-pending"><span class="record-status">\u65b0\u589e\u5f85\u5ba1\u6838</span>${summary(key, item.draft)}</article>`).join(''); return `<section class="info-module module-card multi-record-module" id="module-${key}">${head(key)}<div class="record-card-list">${cards}${additions}</div><button class="add-btn" data-section="${key}" data-action="add">+ ${sections[key].add}</button></section>`; }
function renderInlineSection(key) { const section = state.sections[key], data = getVisibleData(section); const fields = key === 'bank' ? Object.fromEntries(Object.entries(sections[key].fields).filter(([name]) => name !== 'attachment')) : sections[key].fields; const edit = section.status !== 'pending' ? `<button class="inline-edit-icon" data-section="${key}" data-action="edit">&#9998;</button>` : ''; const shown = key === 'bank' ? { ...data, cardNo: maskBankCard(data.cardNo) } : { ...data, phone: maskPhone(data.phone) }; return `<section class="info-module module-card" id="module-${key}">${head(key, edit)}${notice(section)}<div class="detail-card">${rows({ fields }, shown)}</div>${section.status === 'pending' ? `<button class="pending-view" data-section="${key}" data-action="view-pending">\u67e5\u770b\u7533\u8bf7 &gt;</button>` : ''}</section>`; }
function renderHome() { const profile = getVisibleData(state.sections.basic); app.innerHTML = `<div class="app single-page">${nav('my personal info')}<div class="landscape-hero"></div><div class="profile-shell"><section class="profile talent-profile-card"><div class="avatar">A</div><div class="profile-main"><h2>${valueOf(profile.alias)}<small>(${valueOf(profile.name)})</small></h2><p class="profile-org">\u4eba\u529b\u8d44\u6e90\u4e2d\u5fc3 \u00b7 \u5458\u5de5\u5173\u7cfb\u4e13\u5458</p></div></section></div><nav class="profile-anchor-nav"><a href="#module-basic">\u4e2a\u4eba</a><a href="#module-bank">\u94f6\u884c\u5361</a><a href="#module-education">\u6559\u80b2</a><a href="#module-work">\u5c65\u5386</a><a href="#module-family">\u5bb6\u5ead</a><a href="#module-emergency">\u7d27\u6025\u8054\u7cfb\u4eba</a></nav><div class="content profile-content">${renderBasicSection()}${renderInlineSection('bank')}${renderRecordSection('education')}${renderRecordSection('work')}${renderRecordSection('family')}${renderInlineSection('emergency')}<button class="reset" data-action="reset">\u91cd\u7f6e Demo \u6570\u636e</button></div></div>`; }
function formFields(meta, data, allowed = null) { return Object.entries(meta.fields).filter(([key]) => !allowed || allowed.has(key)).map(([key, label]) => `<div class="field"><label for="${key}">${label}</label><input id="${key}" name="${key}" value="${esc(data?.[key] || '')}" required></div>`).join(''); }
function upload(slot, title, hint) { return `<div class="material-slot" data-upload-slot="${slot}"><h3>${title}</h3><p>${hint}</p><button type="button" class="upload-trigger" data-action="upload" data-file-slot="${slot}">+ \u4e0a\u4f20${title}</button></div>`; }
function renderEdit() { const key = route.key, section = state.sections[key], meta = sections[key]; let data = getVisibleData(section), allowed = null, title = `\u7f16\u8f91${meta.title}`, approval = section.kind === 'approval', material = ''; if (key === 'basic') { if (route.mode === 'identity') { allowed = identityFields; title = '\u7f16\u8f91\u8eab\u4efd\u8bc1\u4fe1\u606f'; approval = true; material = `<section class="upload material-grid">${upload('id-front', '\u8eab\u4efd\u8bc1\u6b63\u9762', '\u8bf7\u4e0a\u4f20\u6e05\u6670\u8bc1\u4ef6')}${upload('id-back', '\u8eab\u4efd\u8bc1\u53cd\u9762', '\u8bf7\u4e0a\u4f20\u6e05\u6670\u8bc1\u4ef6')}</section>`; } else if (route.mode === 'household') { allowed = householdFields; title = '\u7f16\u8f91\u6237\u53e3\u4fe1\u606f'; approval = true; material = `<section class="upload">${upload('household-book', '\u6237\u53e3\u672c\u672c\u4eba\u9875', '\u8bf7\u4e0a\u4f20\u6e05\u6670\u6237\u53e3\u672c')}</section>`; } else { allowed = new Set(['email', 'address', 'politicalStatus']); title = '\u7f16\u8f91\u4e2a\u4eba\u4fe1\u606f'; approval = false; } } else if (recordKeys.has(key)) { data = route.recordId ? section.approvedData.find(item => item.id === route.recordId) : {}; title = route.recordId ? `\u7f16\u8f91${meta.title}` : meta.add; approval = key !== 'family' || data?.relation === '\u5b50\u5973'; } else if (key === 'bank') material = `<section class="upload">${upload('bank-card', '\u94f6\u884c\u5361', '\u8bf7\u4e0a\u4f20\u94f6\u884c\u5361\u56fe\u7247')}</section>`; const emergency = key === 'family' && route.recordId ? `<button type="button" class="set-emergency" data-action="set-emergency" data-family-id="${route.recordId}">\u8bbe\u4e3a\u7d27\u6025\u8054\u7cfb\u4eba</button>` : ''; const remove = recordKeys.has(key) && route.recordId ? '<button type="button" class="delete-link" data-action="delete">\u5220\u9664\u672c\u6761\u4fe1\u606f</button>' : ''; app.innerHTML = `<div class="app">${nav(title, true)}<form id="edit-form" class="content">${material}<section class="form-card">${formFields(meta, data, allowed)}</section>${emergency}${remove}</form><footer class="actions"><button class="secondary" data-action="back">\u53d6\u6d88</button><button class="primary" type="submit" form="edit-form">${approval ? '\u63d0\u4ea4\u5ba1\u6838' : '\u4fdd\u5b58'}</button></footer></div>`; files.forEach(file => document.querySelector(`[data-upload-slot="${file.slot}"]`)?.insertAdjacentHTML('beforeend', `<div class="file">${valueOf(file.name)}</div>`)); }
function renderPending() { const section = state.sections[route.key], request = route.requestId ? section.recordRequests.find(item => item.requestId === route.requestId) : null, data = request ? (request.operation === 'delete' ? section.approvedData.find(item => item.id === request.recordId) : request.draft) : getVisibleData(section); app.innerHTML = `<div class="app">${nav('\u7533\u8bf7\u8be6\u60c5', true)}<div class="content"><div class="notice">\u5ba1\u6838\u7ed3\u679c\u5c06\u5728\u540e\u53f0\u5904\u7406\u3002</div><section class="detail-card">${rows(sections[route.key], data)}</section></div><footer class="actions"><button class="danger-btn" data-action="withdraw" data-section="${route.key}" data-request="${route.requestId || ''}">\u64a4\u56de\u7533\u8bf7</button></footer></div>`; }
function render() { route.page === 'home' ? renderHome() : route.page === 'pending' ? renderPending() : renderEdit(); }
function backHome() { route = { page: 'home' }; files = []; render(); }
function openEdit(key, options = {}) { route = { page: 'edit', key, ...options }; files = []; render(); }
function saveRecord(remove = false) { const key = route.key, section = state.sections[key], original = section.approvedData.find(item => item.id === route.recordId), draft = remove ? null : Object.fromEntries(new FormData(document.querySelector('#edit-form'))), operation = remove ? 'delete' : route.recordId ? 'edit' : 'add', approval = key !== 'family' || draft?.relation === '\u5b50\u5973' || original?.relation === '\u5b50\u5973'; try { if (approval) state = submitRecord(state, key, operation, draft, route.recordId, files); else { const records = remove ? section.approvedData.filter(item => item.id !== route.recordId) : route.recordId ? section.approvedData.map(item => item.id === route.recordId ? { ...draft, id: item.id } : item) : [...section.approvedData, { ...draft, id: `f${Date.now()}` }]; state = saveSection(state, key, records); } persist(); backHome(); } catch (error) { window.alert(error.message); } }
app.addEventListener('click', event => { const row = event.target.closest('[data-field-group]'); if (row) return openEdit(row.dataset.section, { mode: row.dataset.fieldGroup }); const card = event.target.closest('[data-record-edit]'); if (card) return openEdit(card.dataset.section, { recordId: card.dataset.recordEdit }); const button = event.target.closest('[data-action]'); if (!button) return; const action = button.dataset.action, key = button.dataset.section || route.key; if (action === 'back') return backHome(); if (action === 'toggle-basic') { basicExpanded = !basicExpanded; return render(); } if (action === 'edit' || action === 'add') return openEdit(key); if (action === 'upload') { files = [...files.filter(item => item.slot !== button.dataset.fileSlot), { slot: button.dataset.fileSlot, name: `${button.parentElement.querySelector('h3').textContent}.jpg` }]; return render(); } if (action === 'delete') return saveRecord(true); if (action === 'set-emergency') { state = submitEmergencyFromFamily(state, button.dataset.familyId); persist(); return backHome(); } if (action === 'view-pending') { route = { page: 'pending', key, requestId: button.dataset.request }; return render(); } if (action === 'withdraw') { state = button.dataset.request ? withdrawRecord(state, key, button.dataset.request) : withdrawSection(state, key); persist(); return backHome(); } if (action === 'reset') { state = createInitialState(); persist(); return render(); } });
app.addEventListener('submit', event => { event.preventDefault(); if (recordKeys.has(route.key)) return saveRecord(); const draft = { ...getVisibleData(state.sections[route.key]), ...Object.fromEntries(new FormData(event.target)) }; try { const approval = route.key !== 'basic' || route.mode === 'identity' || route.mode === 'household'; state = approval ? submitSection(state, route.key, draft, files) : saveSection(state, route.key, draft); persist(); backHome(); } catch (error) { window.alert(error.message); } });
render();
